teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    deadman_buttons: []
    axis_mappings:
      -
        axis: 1 # LeftTrigger Y
        target: linear.x
        scale: 0.22
      -
        axis: 0 # LeftTrigger X
        target: angular.z
        scale: 2.84

