teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 1.0
  stop:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    deadman_buttons: [0]
    message_value:
      -
        target: linear.x
        value: 0.0
      -
        target: linear.y
        value: 0.0
      -
        target: angular.z
        value: 0.0
  clear:
    type: service
    service_name: /clear
    buttons: [6]
  reset:
    type: service
    service_name: /reset
    buttons: [7]
  setpen_off:
    type: service
    service_name: /turtle1/set_pen
    buttons: [0]
    service_request:
      'off': 1
  setpen_on:
    type: service
    service_name: /turtle1/set_pen
    buttons: [1]
    service_request:
      r: 1
      g: 1
      b: 1
      width: 3
      'off': 0      
  draw_shape:
    type: action
    action_name: /shape_server
    action_goal:
      edges: 5
      radius: 1.0
    buttons: [2]
